apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  mysql-root-password: MTIzNA==  # base64 for '1234'
  mysql-password: MTIzNA==       # base64 for '1234'

